CREATE OR REPLACE VIEW PUBLICATION_INFO AS
    SELECT
        PUBLICATION.PUBLICATION_ID,
        PUBLICATION.TITLE,
        PUBLICATION.PUBLICAION_DATE,
        PUBLICTION.DOMAIN,
        COUNT(DISTINCT PUBLICATION_CONTRIBUTOR.RESEARCH_GROUP_ID) AS GROUPS_INVOLVED,
        COUNT(DISTINCT GROUP_MEMBER.STUDENT_ID)                   AS STUDENTS_INVOLVED,
    FROM
        PUBLICATION
        LEFT JOIN PUBLICATION_CONTRIBUTOR
        ON PUBLICATION_CONTRIBUTOR.PUBLICATION_ID = PUBLICATION.ID
        LEFT JOIN GROUP_MEMBER
        ON GROUP_MEMBER.RESEARCH_GROUP_ID = PUBLICATION_CONTRIBUTOR.RESEARCH_GROUP_ID
    GROUP BY
        PUBLICATION.PUBLICATION_ID,
        PUBLICATION.TITLE,
        PUBLICATION.PUBLICAION_DATE,
        PUBLICTION.DOMAIN
    ORDER BY
        PUBLICATION.PUBLICATION_ID;