SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER ADD_ACCOUNT_ID BEFORE
    INSERT ON ACCOUNT FOR EACH ROW
BEGIN
    :NEW.ACCOUNT_ID := GET_ACCOUNT_ID(:NEW.NAME, :NEW.ACC_CODE, :NEW.OPENING_DATE);
END;
/