CREATE TABLE ITEM (
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    SHORT_DESCRIPTION TEXT NOT NULL,
    UNIT_PRICE NUMBER NOT NULL,
    CONSTRAINT PK_ITEM PRIMARY KEY(ID),
    CONSTRAINT FK_BRANCH FOREIGN KEY (ID) REFERENCES BRANCH(ID)
);

CREATE TABLE BRANCH (
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_BRANCH PRIMARY KEY(ID),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT FK_DIVISION FOREIGN KEY (ID) REFERENCES DISTRICT(ID),
);

CREATE TABLE EMPLOYEE (
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(ID),
    CONSTRAINT FK_DEPARTMENT FOREIGN KEY (ID) REFERENCES DEPARTMENT(ID)
);

CREATE TABLE DIVISION (
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_DIVISION PRIMARY KEY(ID)
);

CREATE TABLE DISTRICT(
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_DISTRICT PRIMARY KEY(ID)
);

CREATE TABLE DEPARTMENT (
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY(ID)
);