CREATE TABLE INSTRUCTOR
(
    ID VARCHAR(20) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DEPT_NAME VARCHAR(100),
    SALARY INT,
    CONSTRAINT PK_ID PRIMARY KEY (ID),
    CONSTRAINT SALARY_CHECK CHECK (SALARY > 20000)
);