SELECT * FROM INSTRUCTOR;

SELECT ID, NAME FROM INSTRUCTOR;

SELECT NAME, DEPT_NAME FROM INSTRUCTOR WHERE SALARY > 70000;

SELECT NAME, DEPT_NAME FROM INSTRUCTOR WHERE SALARY >= 80000 AND SALARY <= 100000;

SELECT ID, NAME FROM INSTRUCTOR WHERE DEPT_NAME = 'Comp. Sci.';

SELECT NAME, SALARY FROM INSTRUCTOR WHERE DEPT_NAME = 'Finance';

SELECT ID, NAME FROM INSTRUCTOR WHERE DEPT_NAME = 'Comp. Sci.' OR SALARY > 75000;

SELECT DEPT_NAME FROM INSTRUCTOR;