-- Queries to test the Privileges

--Checking for Student
CREATE USER STUDENT_USER IDENTIFIED BY 1;

GRANT STUDENT TO STUDENT_USER;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO STUDENT_USER;

connect student_user/1;

SELECT
    *
FROM
    C_210042174.ADVISOR;

SELECT
    *
FROM
    C_210042174.COURSE;

UPDATE C_210042174.COURSE
SET
    TITLE='Intro. to Biology'
WHERE
    COURSE_ID='BIO-101';

--Error
INSERT INTO C_210042174.COURSE VALUES (
    'BIO-101',
    'Intro. to Biology',
    'Biology',
    '4'
);

--Error
DELETE FROM C_210042174.COURSE
WHERE
    COURSE_ID='BIO-101';

--Error

--Checking for Course_Teacher
CREATE USER COURSE_TEACHER_USER IDENTIFIED BY 1;

GRANT COURSE_TEACHER TO COURSE_TEACHER_USER;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO COURSE_TEACHER_USER;

connect course_teacher_user/1;

SELECT
    *
FROM
    C_210042174.STUDENT;

SELECT
    *
FROM
    C_210042174.COURSE;

UPDATE C_210042174.COURSE
SET
    TITLE='Intro. to Biology'
WHERE
    COURSE_ID='BIO-101';

--Error
INSERT INTO C_210042174.COURSE VALUES (
    'BIO-101',
    'Intro. to Biology',
    'Biology',
    '4'
);

--Error
DELETE FROM C_210042174.COURSE
WHERE
    COURSE_ID='BIO-101';

--Error

--Checking for Head_of_the_Departments
CREATE USER HOD IDENTIFIED BY 1;

GRANT HEAD_OF_THE_DEPARTMENTS TO HOD;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO HOD;

connect hod/1;

SELECT
    *
FROM
    C_210042174.STUDENT;

SELECT
    *
FROM
    C_210042174.COURSE;

INSERT INTO C_210042174.INSTRUCTOR VALUES (
    '98367',
    'Buu',
    'Comp. Sci.',
    '80000'
);

SELECT
    *
FROM
    C_210042174.INSTRUCTOR;

--Error

--Checking for Administrator
CREATE USER ADMIN_USER IDENTIFIED BY 1;

GRANT ADMINISTRATOR TO ADMIN_USER;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO ADMIN_USER;

connect admin_user/1;

SELECT
    *
FROM
    C_210042174.DEPARTMENT;

SELECT
    *
FROM
    C_210042174.INSTRUCTOR;

UPDATE C_210042174.DEPARTMENT
SET
    BUDGET=100000
WHERE
    DEPT_NAME='Comp. Sci.';

UPDATE C_210042174.DEPARTMENT
SET
    BUILDING='ac2'
WHERE
    DEPT_NAME='Biology';

--Error


--VIEW UPDATED THEN TABLE UPDATED?
--ANS: YES. TABLE IS ALSO UPDATED
GRANT INSERT ON ADVISOR_SELECTION TO COURSE_TEACHER;

INSERT INTO C_210042174.ADVISOR_SELECTION VALUES (
    '98367',
    'Buu',
    'Comp. Sci.'
);

--TO main USER
SELECT
    *
FROM
    ADVISOR_SELECTION;

SELECT
    *
FROM
    INSTRUCTOR;