--TASK 03

--1. STUDENT ROLE. --student_user

CREATE ROLE STUDENT;

GRANT SELECT ON COURSE TO STUDENT;

GRANT SELECT ON ADVISOR TO STUDENT;

--2. COURSE TEACHER. --teacher_user

CREATE ROLE COURSE_TEACHER;

GRANT SELECT ON STUDENT TO COURSE_TEACHER;

GRANT SELECT ON COURSE TO COURSE_TEACHER;

--3. HEAD OF DEPARTMENT ROLE.
CREATE ROLE HEAD_OF_DEPT;

GRANT COURSE_TEACHER TO HEAD_OF_DEPT;

GRANT SELECT, INSERT ON INSTRUCTOR TO HEAD_OF_DEPT;

--4. ADMIN ROLE.

CREATE ROLE ADMIN;

GRANT SELECT ON DEPARTMENT TO ADMIN;

GRANT SELECT ON INSTRUCTOR TO ADMIN;

GRANT UPDATE (BUDGET) ON DEPARTMENT TO ADMIN;

-- DROPPING USERS

DROP USER STUDENT_USER;

DROP USER TEACHER_USER;

DROP USER HOD_USER;

DROP USER ADMIN_USER;

--STUDENT ROLE
CREATE USER STUDENT_USER IDENTIFIED BY 1234;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO STUDENT_USER;

--COURSE TEACHER ROLE
CREATE USER TEACHER_USER IDENTIFIED BY 1234;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO TEACHER_USER;

--HEAD OF DEPT ROLE
CREATE USER HOD_USER IDENTIFIED BY 1234;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO HOD_USER;

--HEAD OF ADMINISTRATION ROLE

CREATE USER ADMIN_USER IDENTIFIED BY 1234;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO ADMIN_USER;

-- ASSIGNING ROLES

GRANT STUDENT TO STUDENT_USER;

GRANT COURSE_TEACHER TO TEACHER_USER;

GRANT HEAD_OF_DEPT TO HOD_USER;

GRANT ADMIN TO ADMIN_USER;