-- Task 3
-- Create Roles

CREATE ROLE STUDENT;

CREATE ROLE COURSE_TEACHER;

CREATE ROLE HOD;

CREATE ROLE ADMINISTRATOR;

-- Grant basic Privileges to Roles

GRANT CREATE SESSION TO STUDENT;

GRANT CREATE SESSION TO COURSE_TEACHER;

GRANT CREATE SESSION TO HOD;

GRANT CREATE SESSION TO ADMINISTRATOR;

-- Grant Specified Privileges to Roles

GRANT SELECT ON ADVISOR TO STUDENT;

GRANT SELECT ON COURSE TO STUDENT;

GRANT SELECT ON STUDENT TO COURSE_TEACHER;

GRANT SELECT ON COURSE TO COURSE_TEACHER;

GRANT SELECT ON STUDENT TO HOD;

GRANT SELECT ON COURSE TO HOD;

GRANT INSERT ON INSTRUCTOR TO HOD;

GRANT SELECT, UPDATE ON DEPARTMENT TO ADMINISTRATOR;

GRANT SELECT ON INSTRUCTOR TO ADMINISTRATOR;

-- Create Users

CREATE USER STUDENT_USER IDENTIFIED BY student123;

CREATE USER TEACHER_USER IDENTIFIED BY teacher123;

CREATE USER HOD_USER IDENTIFIED BY hod123;

CREATE USER ADMIN_USER IDENTIFIED BY admin123;

-- Assign Roles

GRANT STUDENT TO STUDENT_USER;

GRANT COURSE_TEACHER TO TEACHER_USER;

GRANT HOD TO HOD_USER;

GRANT ADMINISTRATOR TO ADMIN_USER;