-- TASK 01

CREATE OR REPLACE VIEW ADVISOR_SELECTION AS
    SELECT
        ID,
        NAME,
        DEPT_NAME
    FROM
        INSTRUCTOR;

-- TASK 02

CREATE OR REPLACE VIEW STUDENT_COUNT AS
    SELECT
        ADVISOR_SELECTION.NAME,
        COUNT(ADVISOR.S_ID)    AS NUMBER_OF_STUDENT
    FROM
        ADVISOR_SELECTION,
        ADVISOR
    WHERE
        ADVISOR_SELECTION.ID=ADVISOR.I_ID
    GROUP BY
        ADVISOR_SELECTION.NAME;