-- Task 1

CREATE VIEW ADVISOR_SELECTION AS
    SELECT
        ID,
        NAME,
        DEPT_NAME
    FROM
        INSTRUCTOR;

-- Task 2

CREATE VIEW STUDENT_COUNT AS
    SELECT
        ADVISOR_SELECTION.NAME,
        COUNT(ADVISOR.S_ID)    AS STUDENT_COUNT
    FROM
        ADVISOR_SELECTION
        LEFT JOIN ADVISOR
        ON ADVISOR_SELECTION.ID = ADVISOR.I_ID
    GROUP BY
        ADVISOR_SELECTION.NAME;