CREATE OR REPLACE FUNCTION GENRE_STATUS (
    GEN_ID IN NUMBER
) RETURN VARCHAR2 IS
    AVG_REVIEW_COUNT_OF_DIFFERENT_GENRES NUMBER := 100;
    AVG_RATING_OF_DIFFERENT_GENRES       NUMBER := 4.5;
    STATUS                               VARCHAR2(50);
    REVIEW_COUNT                         NUMBER;
    AVG_RATING                           NUMBER;
BEGIN
    SELECT
        G.REVIEW_COUNT,
        G.AVG_RATING INTO REVIEW_COUNT,
        AVG_RATING
    FROM
        GENRES G
    WHERE
        G.GEN_ID = GENRE_STATUS.GEN_ID;
    SELECT
        CASE
            WHEN REVIEW_COUNT > AVG_REVIEW_COUNT_OF_DIFFERENT_GENRES AND AVG_RATING < AVG_RATING_OF_DIFFERENT_GENRES THEN
                'Widely Watched'
            WHEN REVIEW_COUNT < AVG_REVIEW_COUNT_OF_DIFFERENT_GENRES AND AVG_RATING > AVG_RATING_OF_DIFFERENT_GENRES THEN
                'Highly Rated'
            WHEN REVIEW_COUNT > AVG_REVIEW_COUNT_OF_DIFFERENT_GENRES AND AVG_RATING > AVG_RATING_OF_DIFFERENT_GENRES THEN
                'People''s Favorite'
            ELSE
                'So So'
        END INTO STATUS
    FROM
        DUAL;
    RETURN STATUS;
END GENRE_STATUS;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(GENRE_STATUS(1));
END;
/