SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER UPDATE_PRINCIPAL_AMOUNT AFTER
    INSERT ON TRANSACTION FOR EACH ROW
BEGIN
    UPDATE BALANCE
    SET
        PRINCIPAL_AMOUNT = PRINCIPAL_AMOUNT + :NEW.AMOUNT
    WHERE
        ACCOUNT_NO = :NEW.ACCOUNT_NO;
END;
/