SET SERVEROUTPUT ON;

ALTER TABLE ACCOUNT ADD ACCOUNT_ID VARCHAR2(30);

UPDATE ACCOUNT
SET
    ACCOUNT_ID = GET_ACCOUNT_ID(
        NAME,
        ACC_CODE,
        OPENING_DATE
    );

ALTER TABLE BALANCE ADD ACCOUNT_NO VARCHAR2(30);

UPDATE BALANCE
SET
    ACCOUNT_NO = (
        SELECT
            ACCOUNT_ID
        FROM
            ACCOUNT
        WHERE
            ACCOUNT.ID = BALANCE.ACC_NO
    );

ALTER TABLE TRANSACTION ADD ACCOUNT_NO VARCHAR2(30);

UPDATE TRANSACTION
SET
    ACCOUNT_NO = (
        SELECT
            ACCOUNT_ID
        FROM
            ACCOUNT
        WHERE
            ACCOUNT.ID = TRANSACTION.ACC_NO
    );

ALTER TABLE BALANCE DROP CONSTRAINT BALANCE_FK;

ALTER TABLE BALANCE DROP CONSTRAINT BALANCE_PK;

ALTER TABLE BALANCE DROP COLUMN ACC_NO;

ALTER TABLE BALANCE ADD CONSTRAINT BALANCE_PK PRIMARY KEY(ACCOUNT_NO);

ALTER TABLE TRANSACTION DROP CONSTRAINT TRANSACTION_FK;

ALTER TABLE TRANSACTION DROP COLUMN ACC_NO;

ALTER TABLE ACCOUNT DROP CONSTRAINT ACCOUNT_PK;

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY(ACCOUNT_ID);

ALTER TABLE ACCOUNT DROP COLUMN ID;

ALTER TABLE BALANCE ADD CONSTRAINT BALANCE_FK FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE TRANSACTION ADD CONSTRAINT TRANSACTION_FK FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_ID);