CREATE TABLE BRANCH (
    BRANCH_ID NUMBER,
    LOCATION VARCHAR2(255) NOT NULL,
    YEAR_OF_ESTABLISHMENT VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_BRANCH PRIMARY KEY(BRANCH_ID),
);

CREATE TABLE EMPLOYEE (
    NATIONAL_ID VARCHAR2(20),
    NAME VARCHAR2(255) NOT NULL,
    BLOOD_GROUP VARCHAR2(5),
    BIRTH_DATE DATE,
    BASE_SALARY NUMBER(10, 2) NOT NULL,
    BRANCH_ID NUMBER,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(NATIONAL_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);

CREATE TABLE SHIFT (
    SHIFT_ID NUMBER PRIMARY KEY,
    SHIFT_TIME TIMESTAMP,
    DAY_OF_WEEK VARCHAR2(10) CHECK (DAYOFWEEK IN ('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')) NOT NULL,
    SHIFT_DURATION NUMBER NOT NULL,
    BRANCH_ID NUMBER,
    EMPLOYEE_ID NUMBER,
    CONSTRAINT PK_SHIFT PRIMARY KEY(SHIFT_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES BRANCH(EMPLOYEE_ID)
);

CREATE TABLE BOOK (
    ISBN_NO CHAR(13),
    BOOK_NAME VARCHAR2(255) NOT NULL,
    BOOK_TITLE VARCHAR2(255) NOT NULL,
    BOOK_AUTHOR VARCHAR2(255),
    BOOK_GENRE VARCHAR2(50),
    BOOK_PRICE NUMBER(10, 2) NOT NULL,
    PUBLISHER_ID NUMBER,
    CONSTRAINT PK_BOOK PRIMARY KEY(ISBN_NO),
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER(PUBLISHER_ID)
);

CREATE TABLE PUBLISHER (
    PUBLISHER_ID NUMBER,
    NAME VARCHAR2(255) UNIQUE NOT NULL,
    CITY VARCHAR2(255) NOT NULL,
    ESTABLISHMENT_YEAR NUMBER,
    CONSTRAINT PK_PUBLISHER PRIMARY KEY(PUBLISHER_ID)
);

CREATE TABLE USER (
    USER_ID NUMBER,
    USER_NAME VARCHAR2(50) NOT NULL,
    DATE_OF_BIRTH DATE,
    HOMETOWN VARCHAR2(255),
    OCCUPATION VARCHAR2(100),
    CONSTRAINT PK_USER PRIMARY KEY(USER_ID)
);

CREATE TABLE ISSUE (
    ISSUE_ID NUMBER,
    ISSUE_DATE DATE NOT NULL,
    NUMBER_OF_DAYS NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    BOOK_ISBN CHAR(13) NOT NULL,
    CONSTRAINT PK_ISSUE PRIMARY KEY(ISSUE_ID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID),
    FOREIGN KEY (BOOK_ISBN) REFERENCES BOOK(ISBN_NO)
);

CREATE TABLE RECORD (
    RECORD_ID NUMBER,
    USER_ID NUMBER NOT NULL,
    BOOK_ISBN CHAR(13) NOT NULL,
    EMPLOYEE_ID VARCHAR2(20),
    CONSTRAINT PK_RECORD PRIMARY KEY(RECORD_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(NATIONAL_ID),
    FOREIGN KEY (BOOK_ISBN) REFERENCES BOOK(ISBN_NO)
);