CREATE OR REPLACE FUNCTION CALCULATE_YEARLY_EARNING (
    MOV_TITLE IN VARCHAR2
) RETURN NUMBER IS
    RELEASE_DATE        DATE;
    TOTAL_REVIEW_COUNT  NUMBER;
    YEARS_SINCE_RELEASE NUMBER;
    YEARLY_EARNING      NUMBER;
BEGIN
    SELECT
        RELEASE_DATE,
        COUNT(*)     AS TOTAL_REVIEW_COUNT INTO RELEASE_DATE,
        TOTAL_REVIEW_COUNT
    FROM
        MOVIE
        JOIN RATING
        ON MOVIE.MOV_ID = RATING.MOV_ID
    WHERE
        MOV_TITLE = CALCULATE_YEARLY_EARNING.MOV_TITLE;
    YEARS_SINCE_RELEASE := (SYSDATE - RELEASE_DATE) / 365;
    IF YEARS_SINCE_RELEASE > 0 THEN
        YEARLY_EARNING := TOTAL_REVIEW_COUNT * 10 / YEARS_SINCE_RELEASE;
        RETURN YEARLY_EARNING;
    ELSE
        RETURN 0;
    END IF;
END CALCULATE_YEARLY_EARNING;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(CALCULATE_YEARLY_EARNING('Trainspotting'));
END;
/