CREATE TABLE STUDENT(
    ID INT,
    NAME VARCHAR2(20),
    CONTACT_NUMBER NUMBER(11),
    DATE_OF_JOINING DATE,
    RESEARCH_GROUP_ID INT,
    CONSTRAINT ST_PK PRIMARY KEY(ID),
);

CREATE TABLE RESEARCH_GROUP(
    ID INT,
    LAB VARCHAR2(20),
    BUDGET INT,
    GROUP_HEAD VARCHAR2(20),
    MEETING_TIME TIME,
    CONSTRAINT RG_PK PRIMARY KEY(ID),
    CONSTRAINT GH_FK FOREIGN KEY (GROUP_HEAD) REFERENCES STUDENT(ID),
);

CREATE TABLE GROUP_MEMBER(
    STUDENT_ID INT,
    RESEARCH_GROUP_ID INT,
    CONSTRAINT GM_PK PRIMARY KEY(STUDENT_ID, RESEARCH_GROUP_ID),
    CONSTRAINT ST_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    CONSTRAINT RG_FK FOREIGN KEY (RESEARCH_GROUP_ID) REFERENCES RESEARCH_GROUP(ID),
);

CREATE TABLE PUBLICATION(
    ID INT,
    TITLE VARCHAR2(20),
    NAME_OF_CONFERENCE VARCHAR2(20),
    PUBLICAION_DATE DATE,
    DOMAIN VARCHAR2(20),
    SUMMARY TEXT,
    CONSTRAINT RW_PK PRIMARY KEY(ID),
);

CREATE TABLE PUBLICATION_CONTRIBUTOR(
    PUBLICATION_ID INT,
    RESEARCH_GROUP_ID INT,
    CONSTRAINT PC_PK PRIMARY KEY(PUBLICATION_ID, RESEARCH_GROUP_ID),
    CONSTRAINT P_FK FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATION(ID),
    CONSTRAINT RG_FK FOREIGN KEY (RESEARCH_GROUP_ID) REFERENCES RESEARCH_GROUP(ID),
);