-- GROUP_HEAD --head_user

CREATE ROLE GROUP_HEAD;

GRANT SELECT ON RESEARCH_GROUP TO GROUP_HEAD;

GRANT UPDATE ON RESEARCH_GROUP TO GROUP_HEAD;

GRANT DELETE ON RESEARCH_GROUP TO GROUP_HEAD;

GRANT SELECT ON PUBLICATION TO GROUP_HEAD;

GRANT INSERT ON PUBLICATION TO GROUP_HEAD;

GRANT UPDATE ON PUBLICATION TO GROUP_HEAD;

-- TEAM MEMBER --member_user

CREATE ROLE TEAM_MEMBER;

GRANT SELECT ON RESEARCH_GROUP TO TEAM_MEMBER;

GRANT SELECT ON PUBLICATION TO TEAM_MEMBER;

GRANT INSERT ON PUBLICATION TO TEAM_MEMBER;

-- USERS

DROP USER HEAD_USER;

DROP USER MEMBER_USER;

CREATE USER HEAD_USER IDENTIFIED BY 1;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO STUDENT_USER;

CREATE USER MEMBER_USER IDENTIFIED BY 1;

GRANT CREATE SESSION, RESOURCE, CREATE TABLESPACE TO TEACHER_USER;

-- ASSIGNING ROLES TO USERS

GRANT GROUP_HEAD TO HEAD_USER;

GRANT TEAM_MEMBER TO MEMBER_USER;

-- DEMONSTRATING ROLES

-- CONNECT head_user

CONNECT head_user/1;

SELECT
    *
FROM
    C_210042174.RESEARCH_GROUP;

SELECT
    *
FROM
    C_210042174.PUBLICATION;

INSERT INTO C_210042174.PUBLICATION VALUES (
    1,
    'Domain of Health',
    'SG_Conference',
    DATE('2021-01-01'),
    'Health',
    'SUMMARY'
);

-- CONNECT member_user

CONNECT member_user/1;

SELECT
    *
FROM
    C_210042174.RESEARCH_GROUP;

SELECT
    *
FROM
    C_210042174.PUBLICATION;

INSERT INTO C_210042174.PUBLICATION VALUES (
    1,
    'Domain of Health',
    'SG_Conference',
    DATE('2021-01-01'),
    'Health',
    'SUMMARY'
);