CREATE TABLE ITEM (
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    SHORT_DESCRIPTION TEXT NOT NULL,
    UNIT_PRICE NUMBER NOT NULL,
    CONSTRAINT PK_ITEM PRIMARY KEY(ID)
);

CREATE TABLE BRANCH (
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_BRANCH PRIMARY KEY(ID),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT FK_DIVISION FOREIGN KEY (ID) REFERENCES DIVISION(ID),
);

CREATE TABLE DIVISION (
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_DIVISION PRIMARY KEY(ID)
);

CREATE TABLE DEPARTMENT (
    ID NUMBER,
    NAME VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY(ID)
);